on:
  workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo Hello from Octo Organization
      - run: |
          cd C:\\actions-runner
          ls
